### ISSUE TITLE
To confirm Project License

### ISSUE THREAD

**Issue by aircha** [avaj-java/installer-maker#20]
If you thank the program owners, I would appreciate it if you could receive a return of a glass of beer

**Comment by aircha** [comment]
For example, what about this?

```
/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <phk@FreeBSD.ORG> wrote this file. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy me a beer in return Poul-Henning Kamp
 * ----------------------------------------------------------------------------
 */
```

**Comment by souljungkim** [comment]
@aircha 
Thank you for your valued participation! 
Let's think positively. 😄

**Comment by souljungkim** [comment]
https://en.wikipedia.org/wiki/Beerware

**Comment by souljungkim** [comment]
라이센스 규칙이 존재하는 것 같습니다. 그에 맞는 것을 해야만 하는 것인지... 고민이 되는군요.
https://github.com/github/choosealicense.com/issues/52

그냥 `MIT` + `BEERWARE`로 실시하려고 합니다.

예로 아래의 프로젝트를 링크합니다. 라이센스 두 개를 달아 놓았네요.  (`MIT` + `BEERWARE`)
https://github.com/reasonableext/reasonable/blob/master/BEERWARE-LICENSE
https://gist.github.com/Loki-Afro/f2162ba55e6ef22c670388d71698f2ce

**Comment by souljungkim** [comment]
not good, but no way 😄 
- MIT: https://github.com/avaj-java/installer-maker/blob/master/LICENSE
- BEERWARE: https://github.com/avaj-java/installer-maker/blob/master/BEERWARE
